

SET IDENTITY_INSERT [dbo].[PermissionRecord] ON
INSERT INTO [dbo].[PermissionRecord] ([Id], [Name], [SystemName], [Category]) VALUES (1, N'Plugins. Access Web Service', N'AccessWebService', N'Plugin')
INSERT INTO [dbo].[PermissionRecord] ([Id], [Name], [SystemName], [Category]) VALUES (2, N'Access admin area', N'AccessAdminPanel', N'Standard')
INSERT INTO [dbo].[PermissionRecord] ([Id], [Name], [SystemName], [Category]) VALUES (3, N'Admin area. Allow Customer Impersonation', N'AllowCustomerImpersonation', N'Customers')
INSERT INTO [dbo].[PermissionRecord] ([Id], [Name], [SystemName], [Category]) VALUES (4, N'Admin area. Manage Products', N'ManageProducts', N'Catalog')
INSERT INTO [dbo].[PermissionRecord] ([Id], [Name], [SystemName], [Category]) VALUES (5, N'Admin area. Manage Categories', N'ManageCategories', N'Catalog')
INSERT INTO [dbo].[PermissionRecord] ([Id], [Name], [SystemName], [Category]) VALUES (6, N'Admin area. Manage Manufacturers', N'ManageManufacturers', N'Catalog')
INSERT INTO [dbo].[PermissionRecord] ([Id], [Name], [SystemName], [Category]) VALUES (7, N'Admin area. Manage Product Reviews', N'ManageProductReviews', N'Catalog')
INSERT INTO [dbo].[PermissionRecord] ([Id], [Name], [SystemName], [Category]) VALUES (8, N'Admin area. Manage Product Tags', N'ManageProductTags', N'Catalog')
INSERT INTO [dbo].[PermissionRecord] ([Id], [Name], [SystemName], [Category]) VALUES (9, N'Admin area. Manage Attributes', N'ManageAttributes', N'Catalog')
INSERT INTO [dbo].[PermissionRecord] ([Id], [Name], [SystemName], [Category]) VALUES (10, N'Admin area. Manage Customers', N'ManageCustomers', N'Customers')
INSERT INTO [dbo].[PermissionRecord] ([Id], [Name], [SystemName], [Category]) VALUES (11, N'Admin area. Manage Vendors', N'ManageVendors', N'Customers')
INSERT INTO [dbo].[PermissionRecord] ([Id], [Name], [SystemName], [Category]) VALUES (12, N'Admin area. Manage Current Carts', N'ManageCurrentCarts', N'Orders')
INSERT INTO [dbo].[PermissionRecord] ([Id], [Name], [SystemName], [Category]) VALUES (13, N'Admin area. Manage Orders', N'ManageOrders', N'Orders')
INSERT INTO [dbo].[PermissionRecord] ([Id], [Name], [SystemName], [Category]) VALUES (14, N'Admin area. Manage Recurring Payments', N'ManageRecurringPayments', N'Orders')
INSERT INTO [dbo].[PermissionRecord] ([Id], [Name], [SystemName], [Category]) VALUES (15, N'Admin area. Manage Gift Cards', N'ManageGiftCards', N'Orders')
INSERT INTO [dbo].[PermissionRecord] ([Id], [Name], [SystemName], [Category]) VALUES (16, N'Admin area. Manage Return Requests', N'ManageReturnRequests', N'Orders')
INSERT INTO [dbo].[PermissionRecord] ([Id], [Name], [SystemName], [Category]) VALUES (17, N'Admin area. Access order country report', N'OrderCountryReport', N'Orders')
INSERT INTO [dbo].[PermissionRecord] ([Id], [Name], [SystemName], [Category]) VALUES (18, N'Admin area. Manage Affiliates', N'ManageAffiliates', N'Promo')
INSERT INTO [dbo].[PermissionRecord] ([Id], [Name], [SystemName], [Category]) VALUES (19, N'Admin area. Manage Campaigns', N'ManageCampaigns', N'Promo')
INSERT INTO [dbo].[PermissionRecord] ([Id], [Name], [SystemName], [Category]) VALUES (20, N'Admin area. Manage Discounts', N'ManageDiscounts', N'Promo')
INSERT INTO [dbo].[PermissionRecord] ([Id], [Name], [SystemName], [Category]) VALUES (21, N'Admin area. Manage Newsletter Subscribers', N'ManageNewsletterSubscribers', N'Promo')
INSERT INTO [dbo].[PermissionRecord] ([Id], [Name], [SystemName], [Category]) VALUES (22, N'Admin area. Manage Polls', N'ManagePolls', N'Content Management')
INSERT INTO [dbo].[PermissionRecord] ([Id], [Name], [SystemName], [Category]) VALUES (23, N'Admin area. Manage News', N'ManageNews', N'Content Management')
INSERT INTO [dbo].[PermissionRecord] ([Id], [Name], [SystemName], [Category]) VALUES (24, N'Admin area. Manage Blog', N'ManageBlog', N'Content Management')
INSERT INTO [dbo].[PermissionRecord] ([Id], [Name], [SystemName], [Category]) VALUES (25, N'Admin area. Manage Widgets', N'ManageWidgets', N'Content Management')
INSERT INTO [dbo].[PermissionRecord] ([Id], [Name], [SystemName], [Category]) VALUES (26, N'Admin area. Manage Topics', N'ManageTopics', N'Content Management')
INSERT INTO [dbo].[PermissionRecord] ([Id], [Name], [SystemName], [Category]) VALUES (27, N'Admin area. Manage Forums', N'ManageForums', N'Content Management')
INSERT INTO [dbo].[PermissionRecord] ([Id], [Name], [SystemName], [Category]) VALUES (28, N'Admin area. Manage Message Templates', N'ManageMessageTemplates', N'Content Management')
INSERT INTO [dbo].[PermissionRecord] ([Id], [Name], [SystemName], [Category]) VALUES (29, N'Admin area. Manage Countries', N'ManageCountries', N'Configuration')
INSERT INTO [dbo].[PermissionRecord] ([Id], [Name], [SystemName], [Category]) VALUES (30, N'Admin area. Manage Languages', N'ManageLanguages', N'Configuration')
INSERT INTO [dbo].[PermissionRecord] ([Id], [Name], [SystemName], [Category]) VALUES (31, N'Admin area. Manage Settings', N'ManageSettings', N'Configuration')
INSERT INTO [dbo].[PermissionRecord] ([Id], [Name], [SystemName], [Category]) VALUES (32, N'Admin area. Manage Payment Methods', N'ManagePaymentMethods', N'Configuration')
INSERT INTO [dbo].[PermissionRecord] ([Id], [Name], [SystemName], [Category]) VALUES (33, N'Admin area. Manage External Authentication Methods', N'ManageExternalAuthenticationMethods', N'Configuration')
INSERT INTO [dbo].[PermissionRecord] ([Id], [Name], [SystemName], [Category]) VALUES (34, N'Admin area. Manage Tax Settings', N'ManageTaxSettings', N'Configuration')
INSERT INTO [dbo].[PermissionRecord] ([Id], [Name], [SystemName], [Category]) VALUES (35, N'Admin area. Manage Shipping Settings', N'ManageShippingSettings', N'Configuration')
INSERT INTO [dbo].[PermissionRecord] ([Id], [Name], [SystemName], [Category]) VALUES (36, N'Admin area. Manage Currencies', N'ManageCurrencies', N'Configuration')
INSERT INTO [dbo].[PermissionRecord] ([Id], [Name], [SystemName], [Category]) VALUES (37, N'Admin area. Manage Measures', N'ManageMeasures', N'Configuration')
INSERT INTO [dbo].[PermissionRecord] ([Id], [Name], [SystemName], [Category]) VALUES (38, N'Admin area. Manage Activity Log', N'ManageActivityLog', N'Configuration')
INSERT INTO [dbo].[PermissionRecord] ([Id], [Name], [SystemName], [Category]) VALUES (39, N'Admin area. Manage ACL', N'ManageACL', N'Configuration')
INSERT INTO [dbo].[PermissionRecord] ([Id], [Name], [SystemName], [Category]) VALUES (40, N'Admin area. Manage Email Accounts', N'ManageEmailAccounts', N'Configuration')
INSERT INTO [dbo].[PermissionRecord] ([Id], [Name], [SystemName], [Category]) VALUES (41, N'Admin area. Manage Stores', N'ManageStores', N'Configuration')
INSERT INTO [dbo].[PermissionRecord] ([Id], [Name], [SystemName], [Category]) VALUES (42, N'Admin area. Manage Plugins', N'ManagePlugins', N'Configuration')
INSERT INTO [dbo].[PermissionRecord] ([Id], [Name], [SystemName], [Category]) VALUES (43, N'Admin area. Manage System Log', N'ManageSystemLog', N'Configuration')
INSERT INTO [dbo].[PermissionRecord] ([Id], [Name], [SystemName], [Category]) VALUES (44, N'Admin area. Manage Message Queue', N'ManageMessageQueue', N'Configuration')
INSERT INTO [dbo].[PermissionRecord] ([Id], [Name], [SystemName], [Category]) VALUES (45, N'Admin area. Manage Maintenance', N'ManageMaintenance', N'Configuration')
INSERT INTO [dbo].[PermissionRecord] ([Id], [Name], [SystemName], [Category]) VALUES (46, N'Admin area. HTML Editor. Manage pictures', N'HtmlEditor.ManagePictures', N'Configuration')
INSERT INTO [dbo].[PermissionRecord] ([Id], [Name], [SystemName], [Category]) VALUES (47, N'Admin area. Manage Schedule Tasks', N'ManageScheduleTasks', N'Configuration')
INSERT INTO [dbo].[PermissionRecord] ([Id], [Name], [SystemName], [Category]) VALUES (48, N'Public store. Display Prices', N'DisplayPrices', N'PublicStore')
INSERT INTO [dbo].[PermissionRecord] ([Id], [Name], [SystemName], [Category]) VALUES (49, N'Public store. Enable shopping cart', N'EnableShoppingCart', N'PublicStore')
INSERT INTO [dbo].[PermissionRecord] ([Id], [Name], [SystemName], [Category]) VALUES (50, N'Public store. Enable wishlist', N'EnableWishlist', N'PublicStore')
INSERT INTO [dbo].[PermissionRecord] ([Id], [Name], [SystemName], [Category]) VALUES (51, N'Public store. Allow navigation', N'PublicStoreAllowNavigation', N'PublicStore')
INSERT INTO [dbo].[PermissionRecord] ([Id], [Name], [SystemName], [Category]) VALUES (52, N'All Settings', N'ManageSettings.AllSettings', N'Configuration')
INSERT INTO [dbo].[PermissionRecord] ([Id], [Name], [SystemName], [Category]) VALUES (55, N'Catalog Settings', N'ManageSettings.CatalogSettings', N'Configuration')
INSERT INTO [dbo].[PermissionRecord] ([Id], [Name], [SystemName], [Category]) VALUES (57, N'General settings', N'ManageSettings.GeneralSettings', N'Configuration')
INSERT INTO [dbo].[PermissionRecord] ([Id], [Name], [SystemName], [Category]) VALUES (58, N'Customer Settings', N'ManageSettings.CustomerSettings', N'Configuration')
INSERT INTO [dbo].[PermissionRecord] ([Id], [Name], [SystemName], [Category]) VALUES (59, N'Shopping Cart Settings', N'ManageSettings.ShoppingCartSettings', N'Configuration')
INSERT INTO [dbo].[PermissionRecord] ([Id], [Name], [SystemName], [Category]) VALUES (60, N'Order Settings', N'ManageSettings.OrderSettings', N'Configuration')
INSERT INTO [dbo].[PermissionRecord] ([Id], [Name], [SystemName], [Category]) VALUES (61, N'Media Settings', N'ManageSettings.MediaSettings', N'Configuration')
INSERT INTO [dbo].[PermissionRecord] ([Id], [Name], [SystemName], [Category]) VALUES (62, N'Tax Settings', N'ManageSettings.TaxSettings', N'Configuration')
INSERT INTO [dbo].[PermissionRecord] ([Id], [Name], [SystemName], [Category]) VALUES (63, N'Shipping Settings', N'ManageSettings.ShippingSettings', N'Configuration')
INSERT INTO [dbo].[PermissionRecord] ([Id], [Name], [SystemName], [Category]) VALUES (64, N'Reward Points', N'ManageSettings.RewardPoints', N'Configuration')
INSERT INTO [dbo].[PermissionRecord] ([Id], [Name], [SystemName], [Category]) VALUES (65, N'Blog Settings', N'ManageSettings.BlogSettings', N'Configuration')
INSERT INTO [dbo].[PermissionRecord] ([Id], [Name], [SystemName], [Category]) VALUES (66, N'News Settings', N'ManageSettings.NewsSettings', N'Configuration')
INSERT INTO [dbo].[PermissionRecord] ([Id], [Name], [SystemName], [Category]) VALUES (67, N'Forum Settings', N'ManageSettings.ForumSettings', N'Configuration')
INSERT INTO [dbo].[PermissionRecord] ([Id], [Name], [SystemName], [Category]) VALUES (68, N'Vendor Settings', N'ManageSettings.VendorSettings', N'Configuration')
SET IDENTITY_INSERT [dbo].[PermissionRecord] OFF
